Update semgrep.yml

diff --git a/.github/workflows/semgrep.yml b/.github/workflows/semgrep.yml
--- a/.github/workflows/semgrep.yml
+++ b/.github/workflows/semgrep.yml
@@ -2,13 +2,15 @@ on:
   pull_request: {}
   push:
     branches:
-    - main
-    - master
-    paths:
-    - .github/workflows/semgrep.yml
+      - main
+      - master
+      paths:
+      - .github/workflows/semgrep.yml
   schedule:
-  - cron: '0 0 * * 0'
+    - cron: '0 0 * * *'
+
 name: Semgrep
+
 jobs:
   semgrep:
     name: Scan
@@ -18,5 +20,20 @@ jobs:
     container:
       image: returntocorp/semgrep
     steps:
-    - uses: actions/checkout@v3
-    - run: semgrep ci
+      - uses: actions/checkout@v3
+
+      - name: Run Semgrep
+        run: |
+          set -e
+          semgrep ci || echo "Semgrep analysis failed. Check the logs for details."
+
+      - name: Check Semgrep Results
+        run: |
+          semgrep_results=$(semgrep --json ci)
+          if [[ $? -eq 0 ]]; then
+            echo "Semgrep analysis succeeded."
+          else
+            echo "Semgrep analysis failed. Check the logs for details."
+            echo "$semgrep_results"
+            exit 1
+          fi
